install ansible prior to running ansible playbook.

diff --git a/jjb/jobs/qcs-master-container-install.yaml b/jjb/jobs/qcs-master-container-install.yaml
--- a/jjb/jobs/qcs-master-container-install.yaml
+++ b/jjb/jobs/qcs-master-container-install.yaml
@@ -29,7 +29,6 @@
         - copyartifact:
                 project: qpc_docker_img_poll
                 filter: quipucords.*.tar.gz
-                target: ${WORKSPACE}/container/
                 stable: true
 
         - shining-panda:
@@ -46,6 +45,18 @@
                 echo "OPTIONS=--log-driver=journald" > docker.conf
                 echo "DOCKER_CERT_PATH=/etc/docker" >> docker.conf
                 sudo cp docker.conf /etc/sysconfig/docker
+
+                set +e # don't want to fail if epel is allready installed
+                if [ "${{DISTRO}}" = "rhel7" ]; then
+                        wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
+                        sudo rpm -ivh epel-release-latest-7.noarch.rpm
+                fi
+                if [ "${{DISTRO}}" = "rhel6" ]; then
+                        wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
+                        sudo rpm -ivh epel-release-6-8.noarch.rpm
+                fi
+                sudo yum -y install ansible
+                set -e
 
                 echo "extract the installer into ${{WORKSPACE}}/install"
                 tar -xvzf ${{WORKSPACE}}/quipucords.install.tar.gz
